//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel
{


    public partial class Contact
    {
        /// <summary>
        /// ltlContactInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ltlContactInfo;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRefresh;

        /// <summary>
        /// ltlContactPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ltlContactPreview;
    }
}
