//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel
{


    public partial class Skills
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// txtSkillName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkillName;

        /// <summary>
        /// rfvSkillName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSkillName;

        /// <summary>
        /// txtIconUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtIconUrl;

        /// <summary>
        /// txtPercentage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPercentage;

        /// <summary>
        /// rvPercentage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvPercentage;

        /// <summary>
        /// txtDisplayOrder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDisplayOrder;

        /// <summary>
        /// btnAddSkill control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddSkill;

        /// <summary>
        /// btnUpdateSkill control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdateSkill;

        /// <summary>
        /// btnCancelEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        /// <summary>
        /// hdnSkillId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSkillId;

        /// <summary>
        /// gvSkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSkills;
    }
}
