//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel
{


    public partial class Experience
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// formTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl formTitle;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// rfvTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;

        /// <summary>
        /// txtCompany control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCompany;

        /// <summary>
        /// rfvCompany control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCompany;

        /// <summary>
        /// txtDuration control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDuration;

        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// rfvDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescription;

        /// <summary>
        /// FileUpload1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;

        /// <summary>
        /// currentImageDiv control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl currentImageDiv;

        /// <summary>
        /// imgCurrent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgCurrent;

        /// <summary>
        /// btnAddExperience control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddExperience;

        /// <summary>
        /// btnUpdateExperience control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdateExperience;

        /// <summary>
        /// btnCancelEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;

        /// <summary>
        /// hdnExperienceId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnExperienceId;

        /// <summary>
        /// hdnCurrentImagePath control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnCurrentImagePath;

        /// <summary>
        /// gvExperience control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvExperience;
    }
}
